apiVersion: v1
kind: Service
metadata:
  name: tael-cli
  labels:
    app.kubernetes.io/name: tael-cli
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tael-cli
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
